services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ims-backend
    container_name: ims-backend
    environment:
      - MONGO_URI=mongodb+srv://muthomi:muthomi@clusterinventory.ufnfd.mongodb.net/inventory?retryWrites=true&w=majority&appName=ClusterInventory
    ports:
      - "8090:8090"
    # depends_on:
    # - "mongo"

  #mongo:
  # image: mongo:latest
  #container_name: ims-mongo
  #volumes:
  #  - mern-data:/data/db
  #ports:
  #  - "27017:27017"
#volumes:
# mern-data:
